// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwYn0bT8OI5ey6RFYdoxJaHRtbidRwqko',
    appId: '1:100384323482:android:b42fae61fee6515f4bac23',
    messagingSenderId: '100384323482',
    projectId: 'flutter-chat-app-5647c',
    storageBucket: 'flutter-chat-app-5647c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXtXT8MQhUN4o3lNczgkR6WuYsCN3NCvg',
    appId: '1:100384323482:ios:2f41ccdc8420d40b4bac23',
    messagingSenderId: '100384323482',
    projectId: 'flutter-chat-app-5647c',
    storageBucket: 'flutter-chat-app-5647c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC8O7rlmQ6iFze-1CNnGIQsvZYTtrMjeI',
    appId: '1:100384323482:web:4d9a8730fdc0480b4bac23',
    messagingSenderId: '100384323482',
    projectId: 'flutter-chat-app-5647c',
    authDomain: 'flutter-chat-app-5647c.firebaseapp.com',
    storageBucket: 'flutter-chat-app-5647c.firebasestorage.app',
  );
}